package typescript

// dtoTemplate generates individual DTO files with io-ts codecs
const dtoTemplate = `// Generated by DtoForge - DO NOT EDIT
{{range .Imports}}{{.}}
{{end}}
{{if .DTO.Description}}
/**
 * {{.DTO.Description}}
 */
{{end}}{{if eq .DTO.Type "enum"}}// Enum: {{.DTO.Name}}
export const {{.DTO.Name}} = t.keyof({
{{range $i, $value := .DTO.EnumValues}}  {{quote $value}}: null{{if ne $i (len $.DTO.EnumValues | add -1)}},{{end}}
{{end}}});

{{if .UseInterfaces}}export interface {{.DTO.Name}} extends t.TypeOf<typeof {{.DTO.Name}}> {}{{else}}export type {{.DTO.Name}} = t.TypeOf<typeof {{.DTO.Name}}>;{{end}}

{{if .GenerateHelpers}}// Validation helper
export const is{{.DTO.Name}} = (value: unknown): value is {{.DTO.Name}} =>
  {{.DTO.Name}}.is(value);

// Decode helper with error handling
export const decode{{.DTO.Name}} = (value: unknown) =>
  {{.DTO.Name}}.decode(value);{{end}}
{{else}}// Schema: {{.DTO.Name}}
{{if .HasRequiredFields}}export const {{.DTO.Name}} = t.intersection([
  t.type({
{{range .DTO.Properties}}{{if .Required}}{{if hasDescription .Description}}    // {{.Description}}
{{end}}    {{safePropertyName .Name}}: {{toIoTsType .Type .Nullable}},
{{end}}{{end}}  }),
  t.partial({
{{range .DTO.Properties}}{{if not .Required}}{{if hasDescription .Description}}    // {{.Description}}
{{end}}    {{safePropertyName .Name}}: {{toIoTsType .Type .Nullable}},
{{end}}{{end}}  })
]){{else}}export const {{.DTO.Name}} = t.partial({
{{range .DTO.Properties}}{{if hasDescription .Description}}  // {{.Description}}
{{end}}  {{safePropertyName .Name}}: {{toIoTsType .Type .Nullable}},
{{end}}}){{end}}

{{if .UseInterfaces}}export interface {{.DTO.Name}} extends t.TypeOf<typeof {{.DTO.Name}}> {}{{else}}export type {{.DTO.Name}} = t.TypeOf<typeof {{.DTO.Name}}>;{{end}}

{{if .GenerateHelpers}}// Validation helper
export const is{{.DTO.Name}} = (value: unknown): value is {{.DTO.Name}} =>
  {{.DTO.Name}}.is(value);

// Decode helper with error handling
export const decode{{.DTO.Name}} = (value: unknown) =>
  {{.DTO.Name}}.decode(value);{{end}}

{{if .GeneratePartialCodecs}}// Partial codec for updates (all fields optional)
export const {{.DTO.Name}}Partial = t.partial({
{{range .DTO.Properties}}  {{safePropertyName .Name}}: {{toIoTsType .Type .Nullable}},
{{end}}});

{{if not $.UseInterfaces}}export type {{.DTO.Name}}Partial = t.TypeOf<typeof {{.DTO.Name}}Partial>;{{end}}{{end}}
{{end}}
`

// indexTemplate generates the main index file that exports everything
const indexTemplate = `// Generated by DtoForge - DO NOT EDIT
// {{.PackageName}} - OpenAPI Schema Validators

{{range .DTOs}}export * from './{{toKebabCase .Name}}';
{{end}}

// Re-export io-ts for convenience
export * as t from 'io-ts';
export { isLeft, isRight } from 'fp-ts/Either';

// Utility type for validation results
export type ValidationResult<T> = {
  success: boolean;
  data?: T;
  errors?: string[];
};

// Generic validation helper
export const validateData = <T>(
  codec: t.Type<T, any, unknown>,
  data: unknown
): ValidationResult<T> => {
  const result = codec.decode(data);

  if (isRight(result)) {
    return {
      success: true,
      data: result.right,
    };
  }

  return {
    success: false,
    errors: formatValidationErrors(result.left),
  };
};

// Format io-ts validation errors into readable messages
const formatValidationErrors = (errors: t.Errors): string[] => {
  return errors.map(error => {
    const path = error.context.map(c => c.key).filter(key => key !== '').join('.');
    const expectedType = error.context[error.context.length - 1]?.type?.name || 'unknown';
    const actualValue = error.value;

    return path
      ? ` + "`" + `Invalid value at '${path}': expected ${expectedType}, got ${typeof actualValue}` + "`" + `
      : ` + "`" + `Invalid value: expected ${expectedType}, got ${typeof actualValue}` + "`" + `;
  });
};

{{if .GenerateSchemaRegistry}}// All available schemas
export const schemas = {
{{range .DTOs}}  {{toCamelCase .Name}}: {{.Name}},
{{end}}};
{{end}}
{{if .GenerateSchemaNames}}// Schema names for runtime access
export const schemaNames = [
{{range .DTOs}}  '{{.Name}}',
{{end}}] as const;

export type SchemaName = typeof schemaNames[number];
{{end}}
`

// packageJSONTemplate generates a package.json for the generated code
const packageJSONTemplate = `{
  "name": "{{.PackageName}}",
  "version": "1.0.0",
  "description": "Generated TypeScript schemas with io-ts validation",
  "main": "index.js",
  "types": "index.d.ts",
  "scripts": {
    "build": "tsc",
    "test": "jest"
  },
  "dependencies": {
    "io-ts": "^2.2.20",
    "io-ts-types": "^0.5.16",
    "fp-ts": "^2.16.1"
  },
  "devDependencies": {
    "@types/node": "^20.0.0",
    "typescript": "^5.0.0",
    "jest": "^29.0.0",
    "@types/jest": "^29.0.0"
  },
  "keywords": ["typescript", "io-ts", "validation", "openapi", "dto"],
  "license": "MIT"
}
`

// Add this fixed singleFileTemplate to internal/typescript/templates.go

// singleFileTemplate generates all DTOs in a single file
const singleFileTemplate = `// Generated by DtoForge (TypeScript) - DO NOT EDIT
// {{.PackageName}} - OpenAPI Schema Validators

{{range .Imports}}{{.}}
{{end}}

{{if .UseInterfaces}}// Forward interface declarations to avoid dependency ordering issues
{{range .DTOs}}{{if .DTO.Description}}/**
 * {{.DTO.Description}}
 */
{{end}}export interface {{.DTO.Name}} extends t.TypeOf<typeof {{.DTO.Name}}> {}
{{if $.GeneratePartialCodecs}}export interface {{.DTO.Name}}Partial extends t.TypeOf<typeof {{.DTO.Name}}Partial> {}
{{end}}
{{end}}

{{end}}{{range .DTOs}}
{{if .DTO.Description}}/**
 * {{.DTO.Description}}
 */
{{end}}
{{if eq .DTO.Type "enum"}}// Enum: {{.DTO.Name}}
export const {{.DTO.Name}} = t.keyof({
{{range .DTO.EnumValues}}  '{{.}}': null,
{{end}}});

{{if not $.UseInterfaces}}export type {{.DTO.Name}} = t.TypeOf<typeof {{.DTO.Name}}>;{{end}}

{{else}}// Schema: {{.DTO.Name}}
{{if .HasRequiredFields}}export const {{.DTO.Name}} = t.intersection([
  t.type({
{{range .DTO.Properties}}{{if .Required}}{{if hasDescription .Description}}    // {{.Description}}
{{end}}    {{safePropertyName .Name}}: {{toIoTsType .Type .Nullable}},
{{end}}{{end}}  }),
  t.partial({
{{range .DTO.Properties}}{{if not .Required}}{{if hasDescription .Description}}    // {{.Description}}
{{end}}    {{safePropertyName .Name}}: {{toIoTsType .Type .Nullable}},
{{end}}{{end}}  })
]){{else}}export const {{.DTO.Name}} = t.partial({
{{range .DTO.Properties}}{{if hasDescription .Description}}  // {{.Description}}
{{end}}  {{safePropertyName .Name}}: {{toIoTsType .Type .Nullable}},
{{end}}}){{end}}

{{if not $.UseInterfaces}}export type {{.DTO.Name}} = t.TypeOf<typeof {{.DTO.Name}}>;{{end}}

{{if $.GeneratePartialCodecs}}// Partial codec for updates (all fields optional)
export const {{.DTO.Name}}Partial = t.partial({
{{range .DTO.Properties}}  {{safePropertyName .Name}}: {{toIoTsType .Type .Nullable}},
{{end}}});

{{if not $.UseInterfaces}}export type {{.DTO.Name}}Partial = t.TypeOf<typeof {{.DTO.Name}}Partial>;{{end}}

{{end}}{{end}}
{{end}}

{{if .GenerateHelpers}}// Re-export io-ts for convenience
export * as t from 'io-ts';
export { isLeft, isRight } from 'fp-ts/Either';

// Utility type for validation results
export type ValidationResult<T> = {
  success: boolean;
  data?: T;
  errors?: string[];
};

// Generic validation helper
export const validateData = <T>(
  codec: t.Type<T, any, unknown>,
  data: unknown
): ValidationResult<T> => {
  const result = codec.decode(data);

  if (isRight(result)) {
    return {
      success: true,
      data: result.right,
    };
  }

  return {
    success: false,
    errors: formatValidationErrors(result.left),
  };
};

// Format io-ts validation errors into readable messages
const formatValidationErrors = (errors: t.Errors): string[] => {
  return errors.map(error => {
    const path = error.context.map(c => c.key).filter(key => key !== '').join('.');
    const expectedType = error.context[error.context.length - 1]?.type?.name || 'unknown';
    const actualValue = error.value;

    return path
      ? ` + "`" + `Invalid value at '${path}': expected ${expectedType}, got ${typeof actualValue}` + "`" + `
      : ` + "`" + `Invalid value: expected ${expectedType}, got ${typeof actualValue}` + "`" + `;
  });
};

{{end}}{{if .GenerateSchemaRegistry}}// All available schemas
export const schemas = {
{{range .DTOs}}  {{toCamelCase .DTO.Name}}: {{.DTO.Name}},
{{end}}};
{{end}}
{{if .GenerateSchemaNames}}// Schema names for runtime access
export const schemaNames = [
{{range .DTOs}}  '{{.DTO.Name}}',
{{end}}] as const;

export type SchemaName = typeof schemaNames[number];
{{end}}
`
