output:
    folder: ./generated
    mode: multiple
    singleFileName: schemas.ts
customTypes:
    date-time:
        ioTsType: DateTimeString
        typeScriptType: DateTimeString
        import: import { DateTimeString } from './branded-types';
    email:
        ioTsType: EmailString.codec
        typeScriptType: EmailString
        import: import { EmailString } from './branded-types';
    uuid:
        ioTsType: UUID.codec
        typeScriptType: UUID
        import: import { UUID } from './branded-types';
generation:
    generatePackageJson: true
    generatePartialCodecs: false
    generateHelpers: false
    generateSchemaRegistry: false
    generateSchemaNames: false
    useInterfaces: true
    processImplicitObjects: false
extensions:
    x-nullable:
        enabled: null
