// Generated by DtoForge (TypeScript) - DO NOT EDIT
// generated-schemas - OpenAPI Schema Validators

import * as t from 'io-ts';
import { DateFromISOString } from 'io-ts-types';


// Interface declarations
export interface Base extends t.TypeOf<typeof Base> {}

export interface Extended extends t.TypeOf<typeof Extended> {}





// Schema: Base
export const Base = t.intersection([
  t.type({
    id: t.string,
  }),
  t.partial({
    createdAt: DateFromISOString,
  })
])






// Schema: Extended (allOf composition)
export const Extended = t.intersection([Base, t.partial({age: t.number, name: t.string})])






