// Generated by DtoForge - DO NOT EDIT
import * as t from 'io-ts';
import { Base64String } from './branded-types';
import { DateTimeString } from './branded-types';
import { URLString } from './branded-types';
import { UUID } from './branded-types';


/**
 * Document with metadata
 */
// Schema: Document
export const Document = t.intersection([
  t.type({
    // Document identifier
    documentId: UUID,
    // Upload timestamp
    uploadedAt: DateTimeString,
  }),
  t.partial({
    // Document content (base64 encoded)
    content: Base64String,
    // Download URL
    downloadUrl: URLString,
  })
])

export type Document = t.TypeOf<typeof Document>;

// Validation helper
export const isDocument = (value: unknown): value is Document =>
  Document.is(value);

// Decode helper with error handling
export const decodeDocument = (value: unknown) =>
  Document.decode(value);

// Partial codec for updates (all fields optional)
export const DocumentPartial = t.partial({
  content: Base64String,
  documentId: UUID,
  downloadUrl: URLString,
  uploadedAt: DateTimeString,
});

export type DocumentPartial = t.TypeOf<typeof DocumentPartial>;

