// Generated by DtoForge - DO NOT EDIT
import * as t from 'io-ts';
import { DateString } from './branded-types';
import { DateTimeString } from './branded-types';
import { URLString } from './branded-types';
import { UUID } from './branded-types';


/**
 * System event with timestamps
 */
// Schema: Event
export const Event = t.intersection([
  t.type({
    // Event identifier
    eventId: UUID,
    // When the event occurred
    timestamp: DateTimeString,
  }),
  t.partial({
    // Date of the event (without time)
    eventDate: DateString,
    // Related resource URL
    resourceUrl: URLString,
    // When the event is scheduled
    scheduledFor: DateTimeString,
  })
])

export type Event = t.TypeOf<typeof Event>;

// Validation helper
export const isEvent = (value: unknown): value is Event =>
  Event.is(value);

// Decode helper with error handling
export const decodeEvent = (value: unknown) =>
  Event.decode(value);

// Partial codec for updates (all fields optional)
export const EventPartial = t.partial({
  eventDate: DateString,
  eventId: UUID,
  resourceUrl: URLString,
  scheduledFor: DateTimeString,
  timestamp: DateTimeString,
});

export type EventPartial = t.TypeOf<typeof EventPartial>;

