// Generated by DtoForge - DO NOT EDIT
import * as t from 'io-ts';
import { Base64String } from './branded-types';
import { DateString } from './branded-types';
import { DateTimeString } from './branded-types';
import { EmailString } from './branded-types';
import { URLString } from './branded-types';
import { UUID } from './branded-types';


/**
 * User with various formatted fields
 */
// Schema: User
export const User = t.intersection([
  t.type({
    // Account creation timestamp
    createdAt: DateTimeString,
    // User's email address
    email: EmailString,
    // Unique user identifier (UUID)
    id: UUID,
  }),
  t.partial({
    // Base64 encoded avatar image
    avatarData: Base64String,
    // User's birth date
    birthDate: DateString,
    // URL to user's profile picture
    profilePicture: URLString,
  })
])

export type User = t.TypeOf<typeof User>;

// Validation helper
export const isUser = (value: unknown): value is User =>
  User.is(value);

// Decode helper with error handling
export const decodeUser = (value: unknown) =>
  User.decode(value);

// Partial codec for updates (all fields optional)
export const UserPartial = t.partial({
  avatarData: Base64String,
  birthDate: DateString,
  createdAt: DateTimeString,
  email: EmailString,
  id: UUID,
  profilePicture: URLString,
});

export type UserPartial = t.TypeOf<typeof UserPartial>;

