// Generated by DtoForge (TypeScript) - DO NOT EDIT
// generated-schemas - OpenAPI Schema Validators

import * as t from 'io-ts';


// Interface declarations
export interface FacetSearchFieldRequest {
  fieldPath?: string | null;
  subFieldFacets?: ReadonlyArray<FacetSearchFieldRequest> | null;
}

export interface SimpleDTO extends t.TypeOf<typeof SimpleDTO> {}

export interface TreeNode {
  children?: ReadonlyArray<TreeNode> | null;
  name: string;
}





// Schema: FacetSearchFieldRequest (recursive)

export const FacetSearchFieldRequest: t.Type<FacetSearchFieldRequest> = t.recursion('FacetSearchFieldRequest', () =>
  t.partial({
    fieldPath: t.union([t.string, t.null]),
    subFieldFacets: t.union([t.readonlyArray(FacetSearchFieldRequest), t.null]),
  })
);





// Schema: SimpleDTO
export const SimpleDTO = t.intersection([
  t.type({
    id: t.string,
  }),
  t.partial({
    label: t.string,
  })
])






// Schema: TreeNode (recursive)

export const TreeNode: t.Type<TreeNode> = t.recursion('TreeNode', () =>
  t.intersection([
    t.type({
      name: t.string,
    }),
    t.partial({
      children: t.union([t.readonlyArray(TreeNode), t.null]),
    })
  ])
);







