// Generated by DtoForge - DO NOT EDIT
import * as t from 'io-ts';


/**
 * Product category
 */
// Schema: Category
export const CategoryCodec = t.type({
  // Category identifier
  id: t.string,
  // Category name
  name: t.string,
  // Parent category ID (for nested categories)
  parentId: t.union([t.string, t.undefined]),
});

export type Category = t.TypeOf<typeof CategoryCodec>;

// Validation helper
export const isCategory = (value: unknown): value is Category =>
  CategoryCodec.is(value);

// Decode helper with error handling
export const decodeCategory = (value: unknown) =>
  CategoryCodec.decode(value);

// Partial codec for updates (all fields optional)
export const CategoryPartialCodec = t.partial({
  id: t.string,
  name: t.string,
  parentId: t.string,
});

export type CategoryPartial = t.TypeOf<typeof CategoryPartialCodec>;

