// Generated by DtoForge - DO NOT EDIT
import * as t from 'io-ts';


/**
 * Product category
 */
// Schema: Category
export const Category = t.intersection([
  t.type({
    // Category identifier
    id: t.string,
    // Category name
    name: t.string,
  }),
  t.partial({
    // Parent category ID (for nested categories)
    parentId: t.string,
  })
])

export type Category = t.TypeOf<typeof Category>;

// Validation helper
export const isCategory = (value: unknown): value is Category =>
  Category.is(value);

// Decode helper with error handling
export const decodeCategory = (value: unknown) =>
  Category.decode(value);

// Partial codec for updates (all fields optional)
export const CategoryPartial = t.partial({
  id: t.string,
  name: t.string,
  parentId: t.string,
});

export type CategoryPartial = t.TypeOf<typeof CategoryPartial>;

