// Generated by DtoForge - DO NOT EDIT
import * as t from 'io-ts';


/**
 * A product in the catalog
 */
// Schema: Product
export const ProductCodec = t.type({
  category: t.union([CategoryCodec, t.undefined]),
  // Product description
  description: t.union([t.string, t.undefined]),
  // Product identifier
  id: t.string,
  // Product name
  name: t.string,
  // Product price
  price: t.number,
});

export type Product = t.TypeOf<typeof ProductCodec>;

// Validation helper
export const isProduct = (value: unknown): value is Product =>
  ProductCodec.is(value);

// Decode helper with error handling
export const decodeProduct = (value: unknown) =>
  ProductCodec.decode(value);

// Partial codec for updates (all fields optional)
export const ProductPartialCodec = t.partial({
  category: CategoryCodec,
  description: t.string,
  id: t.string,
  name: t.string,
  price: t.number,
});

export type ProductPartial = t.TypeOf<typeof ProductPartialCodec>;

