// Generated by DtoForge - DO NOT EDIT
import * as t from 'io-ts';


/**
 * Status enumeration
 */
// Enum: Status
export const Status = t.keyof({
  'active': null,
  'inactive': null,
  'pending': null,
  'archived': null
});

export type Status = t.TypeOf<typeof Status>;

// Validation helper
export const isStatus = (value: unknown): value is Status =>
  Status.is(value);

// Decode helper with error handling
export const decodeStatus = (value: unknown) =>
  Status.decode(value);

