// Generated by DtoForge - DO NOT EDIT
import * as t from 'io-ts';


/**
 * Status enumeration
 */
// Enum: Status
export const StatusValues = {
  'active': null,
  'inactive': null,
  'pending': null,
  'archived': null
} as const;

export const StatusCodec = t.keyof(StatusValues);

export type Status = t.TypeOf<typeof StatusCodec>;

// Validation helper
export const isStatus = (value: unknown): value is Status =>
  StatusCodec.is(value);

// Decode helper with error handling
export const decodeStatus = (value: unknown) =>
  StatusCodec.decode(value);

