// Generated by DtoForge - DO NOT EDIT
import * as t from 'io-ts';


/**
 * A user in the system
 */
// Schema: User
export const User = t.intersection([
  t.type({
    // Unique user identifier
    id: t.string,
    // Full name of the user
    name: t.string,
  }),
  t.partial({
    // User's age (optional)
    age: t.number,
    // User's email address
    email: t.string,
    // Whether the user account is active
    isActive: t.boolean,
  })
])

export type User = t.TypeOf<typeof User>;

// Validation helper
export const isUser = (value: unknown): value is User =>
  User.is(value);

// Decode helper with error handling
export const decodeUser = (value: unknown) =>
  User.decode(value);

// Partial codec for updates (all fields optional)
export const UserPartial = t.partial({
  age: t.number,
  email: t.string,
  id: t.string,
  isActive: t.boolean,
  name: t.string,
});

export type UserPartial = t.TypeOf<typeof UserPartial>;

