// Generated by DtoForge - DO NOT EDIT
import * as t from 'io-ts';


/**
 * A user in the system
 */
// Schema: User
export const UserCodec = t.type({
  // User's age (optional)
  age: t.union([t.number, t.undefined]),
  // User's email address
  email: t.union([t.string, t.undefined]),
  // Unique user identifier
  id: t.string,
  // Whether the user account is active
  isActive: t.union([t.boolean, t.undefined]),
  // Full name of the user
  name: t.string,
});

export type User = t.TypeOf<typeof UserCodec>;

// Validation helper
export const isUser = (value: unknown): value is User =>
  UserCodec.is(value);

// Decode helper with error handling
export const decodeUser = (value: unknown) =>
  UserCodec.decode(value);

// Partial codec for updates (all fields optional)
export const UserPartialCodec = t.partial({
  age: t.number,
  email: t.string,
  id: t.string,
  isActive: t.boolean,
  name: t.string,
});

export type UserPartial = t.TypeOf<typeof UserPartialCodec>;

